---
title: "part 2"
output: html_document
date: "2023-12-25"
---
```{r}
library(dplyr)
library(magrittr)
library(tidyverse)
```

```{r}
# Read data
df <- read.csv("OriginalData.csv")
```

### Processing variable 'Date'

```{r}
data <- df %>% 
  select(Date, Primary.Type, Longitude, Latitude)

data %<>% 
  filter(!Primary.Type %in% c("NON-CRIMINAL", "OTHER NARCOTIC VIOLATION", "PUBLIC INDECENCY", "HUMAN TRAFFICKING", "OBSCENITY"))

data %<>% 
  mutate(Date = as.POSIXct(Date, format = "%m/%d/%Y %I:%M:%S %p"),
         month = format(as.Date(Date, format = "%m/%d/%Y"), "%m"))

data %<>%  
  na.omit()

data %<>% filter(month=="01") %<>% filter(Primary.Type == "ROBBERY")
```

```{r}
library(sf)
library(sp)
library(ggplot2)

library(geosphere)

```

```{r}
for (i in 1:nrow(data)) {
  distances <- numeric(nrow(data))  # Initialize a vector to store distances for each point
  
  for (j in 1:nrow(data)) {
    # Calculate distances between point i and all other points
    distances[j] <- distGeo(c(data$Longitude[i], data$Latitude[i]),c(data$Longitude[j], data$Latitude[j]))
  }
  
  # Store the distances in the data frame
  data$points_within_5km[i] <- sum(distances <= 5000)
}
```




```{r}
# Split the data into training and testing sets
set.seed(42)
split_index <- sample(seq_len(nrow(data)), size = 0.8 * nrow(data))
train_data <- data[split_index, ]
test_data <- data[-split_index, ]

# Fit a linear regression model
model <- lm(points_within_5km ~ Longitude + Latitude, data = train_data)

# Make predictions on the test set
predictions <- predict(model, newdata = test_data)

# Evaluate the model
mse <- mean((test_data$points_within_5km - predictions)^2)
print(paste("Mean Squared Error:", mse))
```

```{r}
# Specify the number of neighbors (k)
k <- 3

# Combine longitude and latitude into matrices
train_coordinates <- cbind(train_data$Longitude, train_data$Latitude)
test_coordinates <- cbind(test_data$Longitude, test_data$Latitude)

# Use KNN for regression to predict the number of crimes on the test set
predicted_crimes <- knn(train = train_coordinates, test = test_coordinates, cl = train_data$points_within_5km)
# Evaluate the performance (you can use various regression metrics)
rmse <- sqrt(mean(as.numeric(predicted_crimes) - test_data$points_within_5km)^2)
print(paste("Root Mean Squared Error (RMSE):", rmse))
```

